POST http://localhost:8080/article_type/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4NTc4MTUsImV4cCI6MTY1NDg2MTQxNSwiaXNzIjoiT2siLCJpZCI6Nywicm9sZSI6IlVTRVIifQ.7keTkGWfguZ6UcJaLjpcEHaj1gbZi41iOvrwVoyU4n8

{
  "key": "muharrir",
  "name_uz": "Muharrir tanlovi",
  "name_ru": "Ruschasi yo'q",
  "name_en": "English no"
}