POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "otabek",
  "surname": "Hoshimxonov",
  "email": "otabekhoshoshimxon@gmail.com",
  "password": "otabek13"

}


